apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: toto
  description: toto
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:default/harness_account_all_users
  lifecycle: experimental
